name: Continuous Integration

on:
  push:
    branches:
      - main  # Adjust this branch name as needed
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:  # Manual run

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the filename as needed

      - name: Build Flask app
        run: |
          # Replace this with the actual command to build your Flask app
          # For example, if you use a script like "app.py", run: python app.py
          python app_build_script.py  # Adjust the script name as needed

      - name: Run unit tests
        run: |
          python -m unittest discover tests  # Adjust the test discovery path

      # Add more steps here for deployment, code analysis, etc. if needed
